let x = 1
$('.button').click(function () {
    ++x
    if (x% 2 == 0) {
        document.body.style.backgroundColor = '#f5f7ff'
        $('#text-color-theme').css('color', 'black')
        $('#text-color-theme').html('DARK')
        $('#toggle-image').attr('src', './images/icon-moon.svg')
        $('#devfinder-h2').css('color', 'black')
        $(".search-div").css('background-color', '#ffffff')
        $(".search-div").addClass('box-shadow')
        $('body').append('<style>#user::placeholder{color:black}</style>')
        $('#user').css('color', 'black')
        $('.main-stats').css('background-color', '#ffffff')
        $('.main-stats').addClass('box-shadow')
        $('#user-txt').css('color', 'black')
        $('.js_bio').css('color', 'black')
        $('#js_join').css('color', 'black')
        $('.some-info').css('background-color', '#f5f7ff')
        $('#repo_js').css('color', '#4b699b')
        $('#followers_js').css('color', '#4b699b')
        $('#following_js').css('color', '#4b699b')
        $('#js_repo').css('color', 'black')
        $('#js_followers').css('color', 'black')
        $('#js_following').css('color', 'black')
        $('#js_location').css('color', '#4b699b')
        $('#js_blog').css('color', '#4b699b')
        $('#js_twitter').css('color', '#4b699b')
        $('#js_github').css('color', '#4b699b')
        $('#location_img').css('filter', 'invert(12%) sepia(34%) saturate(1235%) hue-rotate(184deg) brightness(54%) contrast(89%)')
        $('#twitter_img').css('filter', 'invert(42%) sepia(34%) saturate(1235%) hue-rotate(184deg) brightness(14%) contrast(89%)')
        $('#website_img').css('filter', 'invert(12%) sepia(34%) saturate(1235%) hue-rotate(184deg) brightness(54%) contrast(89%)')
        $('#company_img').css('filter', 'invert(12%) sepia(34%) saturate(1235%) hue-rotate(184deg) brightness(54%) contrast(89%)')
    } else {
        document.body.style.backgroundColor = '#141d2e'
        $('#text-color-theme').css('color', 'white')
        $('#text-color-theme').html('LIGHT')
        $('#toggle-image').attr('src', './images/icon-sun.svg')
        $('#devfinder-h2').css('color', 'white')
        $(".search-div").css('background-color', '#1e2b48')
        $(".search-div").removeClass('box-shadow')
        $('body').append('<style>#user::placeholder{color:white}</style>')
        $('#user').css('color', 'white')
        $('.main-stats').css('background-color', '#1e2b48')
        $('.main-stats').removeClass('box-shadow')
        $('#user-txt').css('color', 'white')
        $('.js_bio').css('color', 'white')
        $('#js_join').css('color', 'white')
        $('.some-info').css('background-color', '#141d2e')
        $('#repo_js').css('color', 'white')
        $('#followers_js').css('color', 'white')
        $('#following_js').css('color', 'white')
        $('#js_repo').css('color', 'white')
        $('#js_followers').css('color', 'white')
        $('#js_following').css('color', 'white')
        $('#js_location').css('color', 'white')
        $('#js_blog').css('color', 'white')
        $('#js_twitter').css('color', 'white')
        $('#js_github').css('color', 'white')
        $('#location_img').css('filter', 'initial')
        $('#twitter_img').css('filter', 'initial')
        $('#website_img').css('filter', 'initial')
        $('#company_img').css('filter', 'initial')
    }

})